PUT http://localhost:3003/api/blogs/67b66187043b1432c455fc46
Content-Type: application/json

{
    "title": "first blog",
    "author": "Caro",
    "url": "bla",
    "likes": 25,
    "user": "67af82970dfde3d26f3d1bbb"
  }